{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use NVNavigationKit, some requirements are needed."}]},{"anchor":"Dependency","level":2,"type":"heading","text":"Dependency"},{"type":"paragraph","inlineContent":[{"type":"text","text":"NVNavigationKit is available from Cocoapods. Add it to your "},{"type":"codeVoice","code":"podfile"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"ruby","code":["platform :ios, '13.0'","","target 'TargetNameForYourApp' do","    use_frameworks!","","    pod 'NVNavigationKit', '~> 0.17.0'","end","","post_install do |installer|","  installer.pods_project.targets.each do |target|","    target.build_configurations.each do |config|","      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'","    end","  end","end"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Don’t forget to install your pod by running:"}]},{"type":"codeListing","syntax":"ruby","code":["pod install --repo-update"]},{"anchor":"Token","level":2,"type":"heading","text":"Token"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need a token with the key "},{"type":"codeVoice","code":"NVibeAPIAccessToken"},{"type":"text","text":" to receive route from the framework. You can add it in your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":null,"code":["<key>NVibeAPIAccessToken<\/key>","<string>YourToken<\/string>"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need a token with the key "},{"type":"codeVoice","code":"NVibeSDKAccessToken"},{"type":"text","text":" to use navigation service from the framework. You can add it in your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":null,"code":["<key>NVibeSDKAccessToken<\/key>","<string>YourToken<\/string>"]},{"anchor":"Http-request-permission","level":2,"type":"heading","text":"Http request permission"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use NVNavigationKit, you need also a temporary permission to allow http request, this will change later. You can add it in your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":null,"code":["<key>NSAppTransportSecurity<\/key>","<dict>","    <key>NSAllowsArbitraryLoads<\/key>","    <true\/>","<\/dict>"]},{"anchor":"Location-tracking","level":2,"type":"heading","text":"Location tracking"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Prior to use navigation service, we need location access enabled when in use from the user."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To achieve this, you need to add the key "},{"type":"codeVoice","code":"NSLocationWhenInUseUsageDescription"},{"type":"text","text":" in your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":" and request it from "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":null,"code":["<key>NSLocationWhenInUseUsageDescription<\/key>","<string>Your location is used to calculate turn-by-turn<\/string>"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since iOS 14, you can set accuracy location level, ensure that "},{"type":"codeVoice","code":"fullAccuracy"},{"type":"text","text":" is set."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/getstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/getstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Get started","role":"article","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService":{"role":"symbol","title":"NVMultimodalService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVMultimodalService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of multimodal events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVMultimodalService"}],"url":"\/documentation\/nvnavigationkit\/nvmultimodalservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService":{"role":"symbol","title":"NVNavigationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseTransitNavigation":{"role":"article","title":"Starting transit navigation","abstract":[{"type":"text","text":"Manage user’s progress over a transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usetransitnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseWalkingNavigation":{"role":"article","title":"Starting walking navigation","abstract":[{"type":"text","text":"Manage user’s progress over a walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usewalkingnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseMultimodalNavigation":{"role":"article","title":"Starting multimodal navigation","abstract":[{"type":"text","text":"Manage user’s progress over multimodal navigation by combining walking navigation and transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usemultimodalnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService":{"role":"symbol","title":"NVCompassService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of compass phone events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassService"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/title","value":"NVMultimodalService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/fragments","value":[{"kind":"identifier","text":"NVMultimodalService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/title","value":"NVNavigationService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/title","value":"NVCompassService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/fragments","value":[{"kind":"identifier","text":"NVCompassService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}