{"seeAlsoSections":[{"title":"Walking navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"title":"LocationError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:15NVNavigationKit13LocationErrorO","modules":[{"name":"NVNavigationKit"}],"navigatorTitle":[{"kind":"identifier","text":"LocationError"}]},"abstract":[{"type":"text","text":"Constants that describe error related to getting current location during walking navigation."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/10Foundation14LocalizedErrorP","doc:\/\/com.nvibe.NVNavigationKit\/SQ","doc:\/\/com.nvibe.NVNavigationKit\/s5ErrorP","doc:\/\/com.nvibe.NVNavigationKit\/SH","doc:\/\/com.nvibe.NVNavigationKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"topicSections":[{"title":"Getting the location error status","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/noConnection","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/noLocation"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/Equatable-Implementations","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/Error-Implementations","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/LocalizedError-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/nvnavigationkit\/locationerror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeObstacleProgress":{"role":"symbol","title":"NVibeObstacleProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacleProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacleProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibeobstacleprogress"},"doc://com.nvibe.NVNavigationKit/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/10Foundation14LocalizedErrorP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/locationerror\/localizederror-implementations"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/RerouteMode":{"role":"symbol","title":"RerouteMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RerouteMode"}],"abstract":[{"type":"text","text":"Constants that describe the mode of reroute during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RerouteMode"}],"url":"\/documentation\/nvnavigationkit\/reroutemode"},"doc://com.nvibe.NVNavigationKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SH"},"doc://com.nvibe.NVNavigationKit/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s5ErrorP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseCustomInstruction":{"role":"article","title":"Use custom instruction during walking navigation","abstract":[{"type":"text","text":"Understand the instruction structure to create your own instruction text during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usecustominstruction"},"doc://com.nvibe.NVNavigationKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SQ"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError/noConnection":{"role":"symbol","title":"LocationError.noConnection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noConnection"}],"abstract":[{"type":"text","text":"The user has not network capabilities."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/noConnection","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/locationerror\/noconnection"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/locationerror\/error-implementations"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError/noLocation":{"role":"symbol","title":"LocationError.noLocation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noLocation"}],"abstract":[{"type":"text","text":"No address available at current user’s location."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/noLocation","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/locationerror\/nolocation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress":{"role":"symbol","title":"NVibeRouteProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteProgress"}],"url":"\/documentation\/nvnavigationkit\/nviberouteprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError":{"role":"symbol","title":"LocationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"abstract":[{"type":"text","text":"Constants that describe error related to getting current location during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"url":"\/documentation\/nvnavigationkit\/locationerror"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate":{"role":"symbol","title":"NVNavigationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated navigation service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate"},"doc://com.nvibe.NVNavigationKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s8SendableP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/locationerror\/equatable-implementations"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeStepProgress":{"role":"symbol","title":"NVibeStepProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStepProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStepProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibestepprogress"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/title","value":"NVibeObstacleProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/fragments","value":[{"kind":"identifier","text":"NVibeObstacleProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/title","value":"NVibeRouteProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/fragments","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/title","value":"NVibeStepProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/fragments","value":[{"kind":"identifier","text":"NVibeStepProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}