{"seeAlsoSections":[{"title":"Walking navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"title":"NVibeRouteProgress","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress","modules":[{"name":"NVNavigationKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeRouteProgress"}]},"abstract":[{"type":"text","text":"The user’s progress along the walking route."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP","doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/SQ","doc:\/\/com.nvibe.NVNavigationKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/obstacleProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/remainingDistance","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/remainingDuration","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/stepProgress"]}],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nviberouteprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/nviberouteprogress"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.nvibe.NVNavigationKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"},"doc://com.nvibe.NVNavigationKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SQ"},"doc://com.nvibe.NVNavigationKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress/remainingDuration":{"role":"symbol","title":"remainingDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remainingDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The remaining duration in second until the end of the route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/remainingDuration","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nviberouteprogress\/remainingduration"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress/obstacleProgress":{"role":"symbol","title":"obstacleProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"obstacleProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeObstacleProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeObstacleProgress"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/obstacleProgress","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nviberouteprogress\/obstacleprogress"},"doc://com.nvibe.NVNavigationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseCustomInstruction":{"role":"article","title":"Use custom instruction during walking navigation","abstract":[{"type":"text","text":"Understand the instruction structure to create your own instruction text during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usecustominstruction"},"doc://com.nvibe.NVNavigationKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SH"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate":{"role":"symbol","title":"NVNavigationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated navigation service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeStepProgress":{"role":"symbol","title":"NVibeStepProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStepProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStepProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibestepprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress/remainingDistance":{"role":"symbol","title":"remainingDistance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remainingDistance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The remaining distance in meter until the end of the route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/remainingDistance","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nviberouteprogress\/remainingdistance"},"doc://com.nvibe.NVNavigationKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject"},"doc://com.nvibe.NVNavigationKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress/stepProgress":{"role":"symbol","title":"stepProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stepProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeStepProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeStepProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/stepProgress","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nviberouteprogress\/stepprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeObstacleProgress":{"role":"symbol","title":"NVibeObstacleProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacleProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacleProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibeobstacleprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress":{"role":"symbol","title":"NVibeRouteProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteProgress"}],"url":"\/documentation\/nvnavigationkit\/nviberouteprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/RerouteMode":{"role":"symbol","title":"RerouteMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RerouteMode"}],"abstract":[{"type":"text","text":"Constants that describe the mode of reroute during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RerouteMode"}],"url":"\/documentation\/nvnavigationkit\/reroutemode"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError":{"role":"symbol","title":"LocationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"abstract":[{"type":"text","text":"Constants that describe error related to getting current location during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"url":"\/documentation\/nvnavigationkit\/locationerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NVibeRouteProgress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Walking navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/title","value":"NVibeStepProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/fragments","value":[{"kind":"identifier","text":"NVibeStepProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/title","value":"NVibeObstacleProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/fragments","value":[{"kind":"identifier","text":"NVibeObstacleProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/title","value":"NVibeRouteProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/fragments","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}