{"seeAlsoSections":[{"title":"Transit navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitProgress"}],"title":"NVibeTransitProgress","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress","modules":[{"name":"NVNavigationKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeTransitProgress"}]},"abstract":[{"type":"text","text":"The user’s progress along the transit."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP","doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/SQ","doc:\/\/com.nvibe.NVNavigationKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress\/currentStop","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress\/nextStop","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress\/remainingStop"]}],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nvibetransitprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/nvibetransitprogress"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitProgress"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeTransitProgress":{"role":"symbol","title":"NVibeTransitProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the transit."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibetransitprogress"},"doc://com.nvibe.NVNavigationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVNavigationKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SQ"},"doc://com.nvibe.NVNavigationKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeTransitProgress/nextStop":{"role":"symbol","title":"nextStop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextStop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The next transit stop the user will reach."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress\/nextStop","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvibetransitprogress\/nextstop"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate":{"role":"symbol","title":"NVTransitServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated transit service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeTransitProgress/currentStop":{"role":"symbol","title":"currentStop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentStop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}],"abstract":[{"type":"text","text":"The last transit stop the user reached."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress\/currentStop","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvibetransitprogress\/currentstop"},"doc://com.nvibe.NVNavigationKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SH"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeTransitProgress/remainingStop":{"role":"symbol","title":"remainingStop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remainingStop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The remaining transit stop to reach."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress\/remainingStop","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvibetransitprogress\/remainingstop"},"doc://com.nvibe.NVNavigationKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP"},"doc://com.nvibe.NVNavigationKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP"},"doc://com.nvibe.NVNavigationKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NVibeTransitProgress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NVibeTransitProgress"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeTransitProgress"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitProgress"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeTransitProgress\/title","value":"NVibeTransitProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeTransitProgress\/fragments","value":[{"kind":"identifier","text":"NVibeTransitProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}