{"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"title":"NVNavigationService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NVNavigationKit@objc(cs)NVNavigationService","modules":[{"name":"NVNavigationKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}]},"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP","doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/SQ","doc:\/\/com.nvibe.NVNavigationKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"topicSections":[{"title":"Creating a navigation service","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/init(delegate:)"]},{"title":"Receiving data from navigation services","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/delegate","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate"]},{"title":"Specifying settings","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/distanceBeforePrepareChangeStep","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/distanceBetweenRightDirection","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/pauseNavigationWhenBadAccuracy","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/maximumAccuracyAllowed"]},{"title":"Running the standard navigation service","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/startNavigation(route:rerouteMode:changeStepMode:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/stopNavigation()","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/getCurrentLocation(completion:)"]}],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nvnavigationservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/nvnavigationservice"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService"},{"type":"text","text":" object uses "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nviberoute"},{"type":"text","text":"  to manage walking navigation."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information, see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation"},{"type":"text","text":"."}]}]}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseMultimodalNavigation":{"role":"article","title":"Starting multimodal navigation","abstract":[{"type":"text","text":"Manage user’s progress over multimodal navigation by combining walking navigation and transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usemultimodalnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/distanceBetweenRightDirection":{"role":"symbol","title":"distanceBetweenRightDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceBetweenRightDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance in meter between each "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdateRightDirectionWith:)"},{"type":"text","text":". The default value of this property is "},{"type":"codeVoice","code":"25"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/distanceBetweenRightDirection","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/distancebetweenrightdirection"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVNavigationServiceDelegate","preciseIdentifier":"s:15NVNavigationKit0A15ServiceDelegateP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates a navigation service object with the specified delegate."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/init(delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/init(delegate:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseWalkingNavigation":{"role":"article","title":"Starting walking navigation","abstract":[{"type":"text","text":"Manage user’s progress over a walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usewalkingnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService":{"role":"symbol","title":"NVMultimodalService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVMultimodalService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of multimodal events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVMultimodalService"}],"url":"\/documentation\/nvnavigationkit\/nvmultimodalservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:willChange:)":{"role":"symbol","title":"navigationService(_:willChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service will reach the next step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:willChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:willchange:)"},"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/nviberoute":{"title":"NVibeRoute","titleInlineContent":[{"type":"text","text":"NVibeRoute"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nviberoute","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nviberoute"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseTransitNavigation":{"role":"article","title":"Starting transit navigation","abstract":[{"type":"text","text":"Manage user’s progress over a transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usetransitnavigation"},"doc://com.nvibe.NVNavigationKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/maximumAccuracyAllowed":{"role":"symbol","title":"maximumAccuracyAllowed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumAccuracyAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The maximum accuracy value used by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/pauseNavigationWhenBadAccuracy"},{"type":"text","text":". The default value of this property is "},{"type":"codeVoice","code":"45"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/maximumAccuracyAllowed","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/maximumaccuracyallowed"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService":{"role":"symbol","title":"NVCompassService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of compass phone events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassService"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didUpdateRightDirectionWith:)":{"role":"symbol","title":"navigationService(_:didUpdateRightDirectionWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateRightDirectionWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that user is on the right track."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdateRightDirectionWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didupdaterightdirectionwith:)"},"doc://com.nvibe.NVNavigationKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SH"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate":{"role":"symbol","title":"NVNavigationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated navigation service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate"},"doc://com.nvibe.NVNavigationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVNavigationKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/distanceBeforePrepareChangeStep":{"role":"symbol","title":"distanceBeforePrepareChangeStep","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceBeforePrepareChangeStep"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance in meter before receiving "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:willChange:)"},{"type":"text","text":". The default value of this property is "},{"type":"codeVoice","code":"25"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/distanceBeforePrepareChangeStep","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/distancebeforepreparechangestep"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/getstarted"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/stopNavigation()":{"role":"symbol","title":"stopNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopNavigation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the generation of navigation updates."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/stopNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/stopnavigation()"},"doc://com.nvibe.NVNavigationKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/getCurrentLocation(completion:)":{"role":"symbol","title":"getCurrentLocation(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCurrentLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"LocationError","preciseIdentifier":"s:15NVNavigationKit13LocationErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a user’s location based on side street along the route during navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/getCurrentLocation(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/getcurrentlocation(completion:)"},"doc://com.nvibe.NVNavigationKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService":{"role":"symbol","title":"NVNavigationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/pauseNavigationWhenBadAccuracy":{"role":"symbol","title":"pauseNavigationWhenBadAccuracy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseNavigationWhenBadAccuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether to pause the walking navigation when accuracy reached the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/maximumAccuracyAllowed"},{"type":"text","text":". The default value of this property is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/pauseNavigationWhenBadAccuracy","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/pausenavigationwhenbadaccuracy"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVNavigationServiceDelegate","preciseIdentifier":"s:15NVNavigationKit0A15ServiceDelegateP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate object to receive update events."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/delegate"},"doc://com.nvibe.NVNavigationKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SQ"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/startNavigation(route:rerouteMode:changeStepMode:)":{"role":"symbol","title":"startNavigation(route:rerouteMode:changeStepMode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startNavigation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rerouteMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RerouteMode","preciseIdentifier":"s:15NVNavigationKit11RerouteModeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"changeStepMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChangeStepDetectionMode","preciseIdentifier":"s:15NVNavigationKit23ChangeStepDetectionModeO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the generation of updates that report the user’s progress during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/startNavigation(route:rerouteMode:changeStepMode:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/startnavigation(route:reroutemode:changestepmode:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NVNavigationService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NVNavigationService"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/title","value":"NVMultimodalService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/fragments","value":[{"kind":"identifier","text":"NVMultimodalService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/title","value":"NVCompassService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/fragments","value":[{"kind":"identifier","text":"NVCompassService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/title","value":"NVNavigationService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}