{"seeAlsoSections":[{"title":"Walking navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationServiceDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nvnavigationservicedelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The methods you use to receive events from an associated navigation service object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"title":"NVNavigationServiceDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:15NVNavigationKit0A15ServiceDelegateP","modules":[{"name":"NVNavigationKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVNavigationServiceDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"],["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService"]]},"topicSections":[{"title":"Handling errors","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didFailToPassTokenWith:)"]},{"title":"Starting transit updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStartWith:)"]},{"title":"Stopping transit updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStopWith:)"]},{"title":"Receiving navigation updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:willChange:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didChange:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdateRightDirectionWith:)"]},{"title":"Receiving reroute updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:shouldRerouteFrom:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didRerouteAlong:with:)"]},{"title":"Receiving obstacle updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didEncounter:)"]},{"title":"Pausing navigation updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didPauseNavigationOnBadAccuracy:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdate:with:snappedTo:with:)"]}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didFailToPassTokenWith:)":{"role":"symbol","title":"navigationService(_:didFailToPassTokenWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToPassTokenWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TokenError","preciseIdentifier":"s:14NVDirectionKit10TokenErrorO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the navigation service was unable to start."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didFailToPassTokenWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didfailtopasstokenwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didEncounter:)":{"role":"symbol","title":"navigationService(_:didEncounter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEncounter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeObstacle","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service reaches the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didEncounter:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didencounter:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseCustomInstruction":{"role":"article","title":"Use custom instruction during walking navigation","abstract":[{"type":"text","text":"Understand the instruction structure to create your own instruction text during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usecustominstruction"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didChange:)":{"role":"symbol","title":"navigationService(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service reaches the next step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress":{"role":"symbol","title":"NVibeRouteProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteProgress"}],"url":"\/documentation\/nvnavigationkit\/nviberouteprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeStepProgress":{"role":"symbol","title":"NVibeStepProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStepProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStepProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibestepprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService":{"role":"symbol","title":"NVNavigationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didPauseNavigationOnBadAccuracy:)":{"role":"symbol","title":"navigationService(_:didPauseNavigationOnBadAccuracy:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPauseNavigationOnBadAccuracy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service location’s accuracy has changed."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didPauseNavigationOnBadAccuracy:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didpausenavigationonbadaccuracy:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/RerouteMode":{"role":"symbol","title":"RerouteMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RerouteMode"}],"abstract":[{"type":"text","text":"Constants that describe the mode of reroute during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RerouteMode"}],"url":"\/documentation\/nvnavigationkit\/reroutemode"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate":{"role":"symbol","title":"NVNavigationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated navigation service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:shouldRerouteFrom:)":{"role":"symbol","title":"navigationService(_:shouldRerouteFrom:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRerouteFrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks the delegate whether the navigation service should reroute."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:shouldRerouteFrom:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:shouldreroutefrom:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError":{"role":"symbol","title":"LocationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"abstract":[{"type":"text","text":"Constants that describe error related to getting current location during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"url":"\/documentation\/nvnavigationkit\/locationerror"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didUpdateRightDirectionWith:)":{"role":"symbol","title":"navigationService(_:didUpdateRightDirectionWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateRightDirectionWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that user is on the right track."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdateRightDirectionWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didupdaterightdirectionwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didRerouteAlong:with:)":{"role":"symbol","title":"navigationService(_:didRerouteAlong:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRerouteAlong"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has rerouted."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didRerouteAlong:with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didreroutealong:with:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didStartWith:)":{"role":"symbol","title":"navigationService(_:didStartWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has started."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStartWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didstartwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:willChange:)":{"role":"symbol","title":"navigationService(_:willChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service will reach the next step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:willChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:willchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didStopWith:)":{"role":"symbol","title":"navigationService(_:didStopWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStopWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has stopped."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStopWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didstopwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeObstacleProgress":{"role":"symbol","title":"NVibeObstacleProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacleProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacleProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibeobstacleprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didUpdate:with:snappedTo:with:)":{"role":"symbol","title":"navigationService(_:didUpdate:with:snappedTo:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"snappedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has updated the user’s location."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdate:with:snappedTo:with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didupdate:with:snappedto:with:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/title","value":"NVibeRouteProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/fragments","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/title","value":"NVibeStepProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/fragments","value":[{"kind":"identifier","text":"NVibeStepProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/title","value":"NVNavigationService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/title","value":"NVibeObstacleProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/fragments","value":[{"kind":"identifier","text":"NVibeObstacleProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}