{"seeAlsoSections":[{"title":"Transit navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitServiceDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nvtransitservicedelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The methods you use to receive events from an associated transit service object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitServiceDelegate"}],"title":"NVTransitServiceDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:15NVNavigationKit24NVTransitServiceDelegateP","modules":[{"name":"NVNavigationKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVTransitServiceDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"],["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService"]]},"topicSections":[{"title":"Handling errors","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didFailToPassTokenWith:)"]},{"title":"Starting transit updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStartWith:)"]},{"title":"Stopping transit updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStopWith:)"]},{"title":"Receiving transit updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didUpdate:with:snappedTo:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:willChange:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didChange:)"]}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:willChange:)":{"role":"symbol","title":"transitService(_:willChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service will reach the next stop."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:willChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:willchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didUpdate:with:snappedTo:)":{"role":"symbol","title":"transitService(_:didUpdate:with:snappedTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"snappedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service has updated the user’s location."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didUpdate:with:snappedTo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didupdate:with:snappedto:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didStartWith:)":{"role":"symbol","title":"transitService(_:didStartWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service has started."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStartWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didstartwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didChange:)":{"role":"symbol","title":"transitService(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service reaches the next stop."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didStopWith:)":{"role":"symbol","title":"transitService(_:didStopWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStopWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service has stopped."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStopWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didstopwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didFailToPassTokenWith:)":{"role":"symbol","title":"transitService(_:didFailToPassTokenWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToPassTokenWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TokenError","preciseIdentifier":"s:14NVDirectionKit10TokenErrorO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the transit service was unable to start."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didFailToPassTokenWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didfailtopasstokenwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate":{"role":"symbol","title":"NVTransitServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated transit service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeTransitProgress":{"role":"symbol","title":"NVibeTransitProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the transit."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibetransitprogress"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeTransitProgress\/title","value":"NVibeTransitProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeTransitProgress\/fragments","value":[{"kind":"identifier","text":"NVibeTransitProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}