{"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"title":"NVTransitService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NVNavigationKit@objc(cs)NVTransitService","modules":[{"name":"NVNavigationKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}]},"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP","doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVNavigationKit\/SQ","doc:\/\/com.nvibe.NVNavigationKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"topicSections":[{"title":"Creating a transit service","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/init(delegate:)"]},{"title":"Receiving data from transit services","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/delegate","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate"]},{"title":"Running the standard transit service","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/startTransitNavigation(departure:arrival:transit:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/stopTransitNavigation()"]}],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nvtransitservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/nvtransitservice"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService"},{"type":"text","text":" object uses "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibetransitinformation"},{"type":"text","text":"  to manage transit navigation."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information, see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation"},{"type":"text","text":"."}]}]}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseMultimodalNavigation":{"role":"article","title":"Starting multimodal navigation","abstract":[{"type":"text","text":"Manage user’s progress over multimodal navigation by combining walking navigation and transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usemultimodalnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/getstarted"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVTransitServiceDelegate","preciseIdentifier":"s:15NVNavigationKit24NVTransitServiceDelegateP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate object to receive update events."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservice\/delegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService/stopTransitNavigation()":{"role":"symbol","title":"stopTransitNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTransitNavigation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the generation of transit updates."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/stopTransitNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservice\/stoptransitnavigation()"},"doc://com.nvibe.NVNavigationKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s7CVarArgP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVTransitServiceDelegate","preciseIdentifier":"s:15NVNavigationKit24NVTransitServiceDelegateP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates a transit service object with the specified delegate."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/init(delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservice\/init(delegate:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseWalkingNavigation":{"role":"article","title":"Starting walking navigation","abstract":[{"type":"text","text":"Manage user’s progress over a walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usewalkingnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService":{"role":"symbol","title":"NVNavigationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservice"},"doc://com.nvibe.NVNavigationKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(pl)NSObject"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService":{"role":"symbol","title":"NVMultimodalService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVMultimodalService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of multimodal events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVMultimodalService"}],"url":"\/documentation\/nvnavigationkit\/nvmultimodalservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate":{"role":"symbol","title":"NVTransitServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated transit service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate"},"doc://com.nvibe.NVNavigationKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseTransitNavigation":{"role":"article","title":"Starting transit navigation","abstract":[{"type":"text","text":"Manage user’s progress over a transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usetransitnavigation"},"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/nvibetransitinformation":{"title":"NVibeTransitInformation","titleInlineContent":[{"type":"text","text":"NVibeTransitInformation"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibetransitinformation","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibetransitinformation"},"doc://com.nvibe.NVNavigationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService":{"role":"symbol","title":"NVCompassService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of compass phone events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassService"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService/startTransitNavigation(departure:arrival:transit:)":{"role":"symbol","title":"startTransitNavigation(departure:arrival:transit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTransitNavigation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"departure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arrival"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the generation of updates that report the user’s progress during transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/startTransitNavigation(departure:arrival:transit:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservice\/starttransitnavigation(departure:arrival:transit:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SH"},"doc://com.nvibe.NVNavigationKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/SQ"},"doc://com.nvibe.NVNavigationKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NVTransitService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/title","value":"NVNavigationService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/title","value":"NVMultimodalService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/fragments","value":[{"kind":"identifier","text":"NVMultimodalService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/title","value":"NVCompassService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/fragments","value":[{"kind":"identifier","text":"NVCompassService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}