{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Instruction contained in "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibestep"},{"type":"text","text":" during walking navigation are identified with a type and a maneuver. For more information about possible type\/maneuver, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.google.com\/spreadsheets\/d\/1NuKxtNdgm3r_npPX-TJAypTgWInNlewkes5SPVpqtpg\/edit?usp=sharing"},{"type":"text","text":"."}]},{"anchor":"Get-instruction","level":3,"type":"heading","text":"Get instruction"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You get the default instruction by doing the following:"}]},{"type":"codeListing","syntax":"swift","code":["var step: NVibeStep","","step.maneuver.instuction \/\/Cross and turn left","step.maneuver.type       \/\/turn","step.maneuver.maneuver   \/\/left"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Generally, instruction are a combination of simple instruction (cross, turn left, etc.) but with the code above, you cannot recognize the combination simply with type\/maneuver. For example, a turn\/left can be “Cross and turn left” or “Turn left”. You need to get the detail to get a list of simple instruction by doing the following:"}]},{"type":"codeListing","syntax":"swift","code":["var step: NVibeStep","","for detail in step.maneuver.details {","    detail.instuction \/\/1: Cross      \/\/2: Turn left","    detail.type       \/\/1: cross      \/\/2: turn","    detail.maneuver   \/\/1: straight   \/\/2: left","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For each detail, you can use the type\/maneuver to set the corresponding simple instruction."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/usecustominstruction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/usecustominstruction"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCustomInstruction","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Understand the instruction structure to create your own instruction text during walking navigation."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Use custom instruction during walking navigation","role":"article","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"seeAlsoSections":[{"title":"Walking navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError"],"generated":true}],"references":{"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/nvibestep":{"title":"NVibeStep","titleInlineContent":[{"type":"text","text":"NVibeStep"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibestep","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibestep"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/RerouteMode":{"role":"symbol","title":"RerouteMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RerouteMode"}],"abstract":[{"type":"text","text":"Constants that describe the mode of reroute during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/RerouteMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RerouteMode"}],"url":"\/documentation\/nvnavigationkit\/reroutemode"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress":{"role":"symbol","title":"NVibeRouteProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteProgress"}],"url":"\/documentation\/nvnavigationkit\/nviberouteprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeStepProgress":{"role":"symbol","title":"NVibeStepProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStepProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStepProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibestepprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"https://docs.google.com/spreadsheets/d/1NuKxtNdgm3r_npPX-TJAypTgWInNlewkes5SPVpqtpg/edit?usp=sharing":{"title":"Type\/Maneuver table","titleInlineContent":[{"type":"text","text":"Type\/Maneuver table"}],"type":"link","identifier":"https:\/\/docs.google.com\/spreadsheets\/d\/1NuKxtNdgm3r_npPX-TJAypTgWInNlewkes5SPVpqtpg\/edit?usp=sharing","url":"https:\/\/docs.google.com\/spreadsheets\/d\/1NuKxtNdgm3r_npPX-TJAypTgWInNlewkes5SPVpqtpg\/edit?usp=sharing"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeObstacleProgress":{"role":"symbol","title":"NVibeObstacleProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacleProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacleProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibeobstacleprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate":{"role":"symbol","title":"NVNavigationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated navigation service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/LocationError":{"role":"symbol","title":"LocationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationError"}],"abstract":[{"type":"text","text":"Constants that describe error related to getting current location during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/LocationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationError"}],"url":"\/documentation\/nvnavigationkit\/locationerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Walking navigation","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/title","value":"NVibeRouteProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/fragments","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/title","value":"NVibeStepProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/fragments","value":[{"kind":"identifier","text":"NVibeStepProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/title","value":"NVibeObstacleProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/fragments","value":[{"kind":"identifier","text":"NVibeObstacleProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}