{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"},{"type":"text","text":" object is used to start and stop the compass of the user’s phone. The compass will report the angle towards which the head’s phone is pointing."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To use it correctly, make sure that the user holds his phone in front of them like a compass."}]}],"type":"aside","name":"Important"},{"anchor":"Create-a-compass-service-object","level":3,"type":"heading","text":"Create a compass service object"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use the compass, create a compass service object and set the correct delegate to receive update events."}]},{"type":"codeListing","syntax":"swift","code":["import NVNavigationKit","","class MyClass: UIViewController: NVCompassServiceDelegate {","    private var compassService: NVCompassService!","","    override func viewDidLoad() {","        compassService = NVCompassService(delegate: this)","    }","","    func compassService(_ service: NVCompassService, didCompassUpdateWith direction: CLLocationDirection, didCompassTrigger: Bool) {","        ","    }","}"]},{"anchor":"Start-compass","level":3,"type":"heading","text":"Start compass"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To start the compass service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService\/startCompass(direction:retrieveDirectionNavigation:)"},{"type":"text","text":" method. The compass service has a feature to trigger event and stop itself automatically when a desired angle is reached. The threshold of detection is +-14°."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, the following code will trigger event when the compass reaches 90°:"}]},{"type":"codeListing","syntax":"swift","code":["import NVNavigationKit","","class MyClass: UIViewController: NVCompassServiceDelegate {","    private var compassService: NVCompassService!","","    override func viewDidLoad() {","        compassService = NVCompassService(delegate: this)","        compassService.startCompass(direction: 90)","    }","","    func compassService(_ service: NVCompassService, didCompassUpdateWith direction: CLLocationDirection, didCompassTrigger: Bool) {","        \/\/When the compass reaches an angle between 76° and 104°, the didCompassTrigger value will be true and the compass service will stop.","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"During walking navigation, it’s useful to help the user to orientate himself to the right direction. You can trigger a vibration when the user points to the direction of the route for example. If you use compass service while a walking navigation is running and you don’t know what angle the user need to follow, you can set "},{"type":"codeVoice","code":"retrieveDirectionNavigation"},{"type":"text","text":" parameter to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to use it automatically."}]},{"type":"codeListing","syntax":"swift","code":["import NVNavigationKit","","class MyClass: UIViewController: NVCompassServiceDelegate {","    private var compassService: NVCompassService!","","    override func viewDidLoad() {","        compassService = NVCompassService(delegate: this)","        compassService.startCompass(retrieveDirectionNavigation: true)","    }","","    func compassService(_ service: NVCompassService, didCompassUpdateWith direction: CLLocationDirection, didCompassTrigger: Bool) {","        \/\/On the current navigation, the user need to follow an angle of 180°.","        \/\/When the compass reaches an angle between 66° and 194°, the didCompassTrigger value will be true and the compass service will stop.","    }","}"]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you don’t provide desired angle or use "},{"type":"codeVoice","code":"retrieveDirectionNavigation"},{"type":"text","text":" while no walking navigation is running, the compass will report direction indefinitely and never trigger. You can use it like this also if you want to implement your own trigger detection."}]}],"type":"aside","name":"Important"},{"anchor":"Stop-compass","level":3,"type":"heading","text":"Stop compass"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To stop the compass service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService\/stopCompass()"},{"type":"text","text":" method. If the compass reached the desired angle set at the start, the compass service will automatically stop."}]},{"type":"codeListing","syntax":"swift","code":["compassService.stopCompass()"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/usecompass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/usecompass"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseCompass","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Retrieve phone’s compass data."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Starting compass","role":"article","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"seeAlsoSections":[{"title":"Compass","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassServiceDelegate"],"generated":true}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassServiceDelegate":{"role":"symbol","title":"NVCompassServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated compass service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservicedelegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService":{"role":"symbol","title":"NVCompassService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of compass phone events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassService"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService/startCompass(direction:retrieveDirectionNavigation:)":{"role":"symbol","title":"startCompass(direction:retrieveDirectionNavigation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCompass"},{"kind":"text","text":"("},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"retrieveDirectionNavigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the generation of updates that report the compass current direction."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService\/startCompass(direction:retrieveDirectionNavigation:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvcompassservice\/startcompass(direction:retrievedirectionnavigation:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService/stopCompass()":{"role":"symbol","title":"stopCompass()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCompass"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the generation of compass direction updates."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService\/stopCompass()","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvcompassservice\/stopcompass()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Compass","identifiers":[],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/title","value":"NVCompassService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/fragments","value":[{"kind":"identifier","text":"NVCompassService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}