{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService"},{"type":"text","text":" object is used to start and stop the multimodal navigation. The navigation will report events to follow the user’s progress over the different multimodal step."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You will combine this service with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService"},{"type":"text","text":" to manage a complete multimodal navigation."}]},{"anchor":"Create-a-multimodal-service-object","level":3,"type":"heading","text":"Create a multimodal service object"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use the multimodal service, create a multimodal service object and set the correct delegate to receive update events."}]},{"type":"codeListing","syntax":"swift","code":["import NVDirectionKit","import NVNavigationKit","","class MyClass: UIViewController: NVMultimodalServiceDelegate {","    private var multimodalService: NVMultimodalService!","","    override func viewDidLoad() {","        multimodalService = NVMultimodalService(delegate: this)","    }","","    func multimodalService(_ service: NVMultimodalService, from route: NVDirectionKit.NVibeMultimodalRoute, didChange multimodalStep: NVDirectionKit.NVibeMultimodalStep, with remainingMultimodalStep: Int) {","        ","    }","","    ...","}"]},{"anchor":"Start-the-multimodal-navigation","level":3,"type":"heading","text":"Start the multimodal navigation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To start the multimodal service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService\/startMultimodalNavigation(departure:arrival:route:)"},{"type":"text","text":" method. Prior, you need to request a multimodal route. For more information, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getmultimodalroute"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["var multimodalRoute: NVibeMultimodalRoute","","multimodalService.startMultimodalNavigation(departure: multimodalRoute.startAddress, arrival: multimodalRoute.endAddress, route: multimodalRoute)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the multimodal service is unable to start, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalServiceDelegate\/multimodalService(_:didFailToPassTokenWith:)"},{"type":"text","text":" method is called. Otherwise, it starts the update loop."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibemultimodalroute"},{"type":"text","text":" is composed with one or more "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibemultimodalstep"},{"type":"text","text":". Each step can be a walking step or a transit step. The multimodal service helps you to follow the progress over this multimodal step."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The update loop send two events. First, it asks you if you want to start the next multimodal step with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalServiceDelegate\/multimodalService(_:from:shouldGoToNext:with:)"},{"type":"text","text":". If you return "},{"type":"codeVoice","code":"true"},{"type":"text","text":", it will tell you to start a walking or transit navigation with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalServiceDelegate\/multimodalService(_:from:didChange:with:)"},{"type":"text","text":"."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalServiceDelegate\/multimodalService(_:from:shouldGoToNext:with:)"},{"type":"text","text":" is not called for the first multimodal step."}]}],"type":"aside","name":"Important"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the multimodal step is a walking step, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation"},{"type":"text","text":" and when the multimodal step is a transit step, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["func multimodalService(_ service: NVMultimodalService, from route: NVDirectionKit.NVibeMultimodalRoute, shouldGoToNext multimodalStep: NVDirectionKit.NVibeMultimodalStep, with remainingMultimodalStep: Int) -> Bool {","    return true","}","","func multimodalService(_ service: NVMultimodalService, from route: NVDirectionKit.NVibeMultimodalRoute, didChange multimodalStep: NVDirectionKit.NVibeMultimodalStep, with remainingMultimodalStep: Int) {","    if multimodalStep.isWalkingStep() {","        \/\/You can calculate a walking route for the walking step here.","        NVDirection.shared.getNavigationRoute(from: multimodalStep.startAddress, to: multimodalStep.endAddress) { (result, error) in","            guard result != nil, error == nil else {","                \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","                return","            }","            \/\/You receive the calculated route here and additional data.","            navigationService.startNavigation(route: result.route)","        }","    } else if multimodalStep.isTransitStep(), let information = multimodalStep.information.getTransitInformation() {","        \/\/You have all the data needed about the transit to take.","        print(\"Take the \\(information.type) \\(information.line) direction \\(information.headsign) from \\(information.departureStop.address) to \\(information.arrivalStop.address)\")","        transitServie.startTransitNavigation(departure: information.departureStop, arrival: information.arrivalStop, transit: information)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the corresponding navigation is finished, it will ask you again for the next multimodal step, etc. If you want to start the next multimodal step without finishing the last navigation, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService\/skipMultimodalStepNavigation()"},{"type":"text","text":"."}]},{"anchor":"Stop-the-multimodal-navigation","level":3,"type":"heading","text":"Stop the multimodal navigation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To stop the transit service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService\/stopMultimodalNavigation()"},{"type":"text","text":" method. If the user reaches the last multimodal step, the multimodal service will stop automatically."}]},{"type":"codeListing","syntax":"swift","code":["multimodalService.stopMultimodalNavigation()"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/usemultimodalnavigation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/usemultimodalnavigation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manage user’s progress over multimodal navigation by combining walking navigation and transit navigation."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Starting multimodal navigation","role":"article","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/getstarted"},"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/nvibemultimodalroute":{"title":"NVibeMultimodalRoute","titleInlineContent":[{"type":"text","text":"NVibeMultimodalRoute"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibemultimodalroute","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibemultimodalroute"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService":{"role":"symbol","title":"NVMultimodalService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVMultimodalService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of multimodal events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVMultimodalService"}],"url":"\/documentation\/nvnavigationkit\/nvmultimodalservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalServiceDelegate/multimodalService(_:from:didChange:with:)":{"role":"symbol","title":"multimodalService(_:from:didChange:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multimodalService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVMultimodalService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVMultimodalService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that new multimodal step has started."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalServiceDelegate\/multimodalService(_:from:didChange:with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvmultimodalservicedelegate\/multimodalservice(_:from:didchange:with:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService/skipMultimodalStepNavigation()":{"role":"symbol","title":"skipMultimodalStepNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipMultimodalStepNavigation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Forces the multimodal service to start the next multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService\/skipMultimodalStepNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvmultimodalservice\/skipmultimodalstepnavigation()"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalServiceDelegate/multimodalService(_:from:shouldGoToNext:with:)":{"role":"symbol","title":"multimodalService(_:from:shouldGoToNext:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multimodalService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVMultimodalService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVMultimodalService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldGoToNext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks the delegate whether the multimodal service should start the next multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalServiceDelegate\/multimodalService(_:from:shouldGoToNext:with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvmultimodalservicedelegate\/multimodalservice(_:from:shouldgotonext:with:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseWalkingNavigation":{"role":"article","title":"Starting walking navigation","abstract":[{"type":"text","text":"Manage user’s progress over a walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usewalkingnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalServiceDelegate/multimodalService(_:didFailToPassTokenWith:)":{"role":"symbol","title":"multimodalService(_:didFailToPassTokenWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multimodalService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVMultimodalService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVMultimodalService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToPassTokenWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TokenError","preciseIdentifier":"s:14NVDirectionKit10TokenErrorO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the multimodal service was unable to start."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalServiceDelegate\/multimodalService(_:didFailToPassTokenWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvmultimodalservicedelegate\/multimodalservice(_:didfailtopasstokenwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService":{"role":"symbol","title":"NVNavigationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseTransitNavigation":{"role":"article","title":"Starting transit navigation","abstract":[{"type":"text","text":"Manage user’s progress over a transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usetransitnavigation"},"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/getmultimodalroute":{"title":"Getting multimodal route","titleInlineContent":[{"type":"text","text":"Getting multimodal route"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getmultimodalroute","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getmultimodalroute"},"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/nvibemultimodalstep":{"title":"NVibeMultimodalStep","titleInlineContent":[{"type":"text","text":"NVibeMultimodalStep"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibemultimodalstep","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/nvibemultimodalstep"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService/startMultimodalNavigation(departure:arrival:route:)":{"role":"symbol","title":"startMultimodalNavigation(departure:arrival:route:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startMultimodalNavigation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"departure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arrival"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the generation of updates that report the multimodal current step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService\/startMultimodalNavigation(departure:arrival:route:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvmultimodalservice\/startmultimodalnavigation(departure:arrival:route:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService":{"role":"symbol","title":"NVCompassService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of compass phone events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassService"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService/stopMultimodalNavigation()":{"role":"symbol","title":"stopMultimodalNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopMultimodalNavigation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the generation of multimodal updates."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService\/stopMultimodalNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvmultimodalservice\/stopmultimodalnavigation()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/title","value":"NVMultimodalService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/fragments","value":[{"kind":"identifier","text":"NVMultimodalService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/title","value":"NVNavigationService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/title","value":"NVCompassService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/fragments","value":[{"kind":"identifier","text":"NVCompassService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}