{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService"},{"type":"text","text":" object is used to start and stop the transit navigation. The navigation will report events to guide the user during transit step."}]},{"anchor":"Create-a-transit-service-object","level":3,"type":"heading","text":"Create a transit service object"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use the transit service, create a transit service object and set the correct delegate to receive update events."}]},{"type":"codeListing","syntax":"swift","code":["import NVDirectionKit","import NVNavigationKit","","class MyClass: UIViewController: NVTransitServiceDelegate {","    private var transitService: NVTransitService!","","    override func viewDidLoad() {","        transitService = NVTransitService(delegate: this)","    }","","    func transitService(_ service: NVTransitService, didStartWith progress: NVibeTransitProgress) {","        ","    }","","    ...","","    func transitService(_ service: NVTransitService, didStopWith progress: NVibeTransitProgress) {","        ","    }","}"]},{"anchor":"Start-the-transit-navigation","level":3,"type":"heading","text":"Start the transit navigation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To start the transit service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/startTransitNavigation(departure:arrival:transit:)"},{"type":"text","text":" method. Prior, you need to request a multimodal route and use the information contains in transit multimodal step. For more information, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getmultimodalroute"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["var transitStepInformation: NVibeTransitInformation","","transitService.startTransitNavigation(departure: transitStepInformation.departureStop, arrival: transitStepInformation.arrivalStop, transit: transitStepInformation)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the transit service starts correctly, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStartWith:)"},{"type":"text","text":" method is called. Otherwise, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didFailToPassTokenWith:)"},{"type":"text","text":" method is called."}]},{"type":"codeListing","syntax":"swift","code":["func transitService(_ service: NVTransitService, didStartWith progress: NVibeTransitProgress) {","    \/\/The transit service starts","    print(\"The departure stop is \\(progress.currentStop.address)\")","}","","func transitService(_ service: NVTransitService, didFailToPassTokenWith error: NVDirectionKit.TokenError) {","    \/\/A error occurred.","}",""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user’s location updates, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didUpdate:with:snappedTo:)"},{"type":"text","text":" method is called. You can update the user’s location on your map."}]},{"type":"codeListing","syntax":"swift","code":["func transitService(_ service: NVTransitService, didUpdate progress: NVibeTransitProgress, with rawLocation: CLLocation, snappedTo location: CLLocation) {","    print(\"The user moves to \\(location.coordinate)\")","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user will reach the next stop, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:willChange:)"},{"type":"text","text":" method is called. You can inform the user about the next stop."}]},{"type":"codeListing","syntax":"swift","code":["func transitService(_ service: NVTransitService, willChange progress: NVibeTransitProgress) {","    print(\"The next stop will be \\(progress.nextStop?.address)\")","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user reaches the next stop, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didChange:)"},{"type":"text","text":" method is called. You can inform the user about the current stop."}]},{"type":"codeListing","syntax":"swift","code":["func transitService(_ service: NVTransitService, didChange progress: NVibeTransitProgress) {","    print(\"The current stop is \\(progress.currentStop.address), you will have \\(progress.remainingStop) stops left\")","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user reaches the last stop, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStopWith:)"},{"type":"text","text":" method is called. You can inform the user about the current stop that it’s the last one so the user need to get off. The transit service will stop automatically."}]},{"type":"codeListing","syntax":"swift","code":["func transitService(_ service: NVTransitService, didStopWith progress: NVibeTransitProgress) {","    print(\"The last stop is \\(progress.currentStop.address), you need to get off here\")","}"]},{"anchor":"Stop-the-transit-navigation","level":3,"type":"heading","text":"Stop the transit navigation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To stop the transit service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/stopTransitNavigation()"},{"type":"text","text":" method. If the user reaches the last stop, the transit service will stop automatically."}]},{"type":"codeListing","syntax":"swift","code":["transitService.stopTransitNavigation()"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/usetransitnavigation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/usetransitnavigation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manage user’s progress over a transit navigation."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Starting transit navigation","role":"article","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService/startTransitNavigation(departure:arrival:transit:)":{"role":"symbol","title":"startTransitNavigation(departure:arrival:transit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTransitNavigation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"departure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arrival"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the generation of updates that report the user’s progress during transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/startTransitNavigation(departure:arrival:transit:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservice\/starttransitnavigation(departure:arrival:transit:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseMultimodalNavigation":{"role":"article","title":"Starting multimodal navigation","abstract":[{"type":"text","text":"Manage user’s progress over multimodal navigation by combining walking navigation and transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usemultimodalnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:willChange:)":{"role":"symbol","title":"transitService(_:willChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service will reach the next stop."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:willChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:willchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService":{"role":"symbol","title":"NVCompassService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of compass phone events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassService"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService":{"role":"symbol","title":"NVMultimodalService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVMultimodalService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of multimodal events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVMultimodalService"}],"url":"\/documentation\/nvnavigationkit\/nvmultimodalservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/getstarted"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseWalkingNavigation":{"role":"article","title":"Starting walking navigation","abstract":[{"type":"text","text":"Manage user’s progress over a walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usewalkingnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didFailToPassTokenWith:)":{"role":"symbol","title":"transitService(_:didFailToPassTokenWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToPassTokenWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TokenError","preciseIdentifier":"s:14NVDirectionKit10TokenErrorO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the transit service was unable to start."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didFailToPassTokenWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didfailtopasstokenwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didUpdate:with:snappedTo:)":{"role":"symbol","title":"transitService(_:didUpdate:with:snappedTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"snappedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service has updated the user’s location."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didUpdate:with:snappedTo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didupdate:with:snappedto:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didChange:)":{"role":"symbol","title":"transitService(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service reaches the next stop."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService":{"role":"symbol","title":"NVNavigationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService/stopTransitNavigation()":{"role":"symbol","title":"stopTransitNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTransitNavigation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the generation of transit updates."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService\/stopTransitNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservice\/stoptransitnavigation()"},"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/getmultimodalroute":{"title":"Getting multimodal route","titleInlineContent":[{"type":"text","text":"Getting multimodal route"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getmultimodalroute","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getmultimodalroute"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didStopWith:)":{"role":"symbol","title":"transitService(_:didStopWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStopWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service has stopped."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStopWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didstopwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didStartWith:)":{"role":"symbol","title":"transitService(_:didStartWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service has started."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didStartWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didstartwith:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/title","value":"NVCompassService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/fragments","value":[{"kind":"identifier","text":"NVCompassService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/title","value":"NVMultimodalService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/fragments","value":[{"kind":"identifier","text":"NVMultimodalService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/title","value":"NVNavigationService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}