{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService"},{"type":"text","text":" object is used to start and stop the walking navigation. The navigation will report events to guide the user during walking step."}]},{"anchor":"Create-a-navigation-service-object","level":3,"type":"heading","text":"Create a navigation service object"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use the navigation service, create a navigation service object and set the correct delegate to receive update events."}]},{"type":"codeListing","syntax":"swift","code":["import NVDirectionKit","import NVNavigationKit","","class MyClass: UIViewController: NVNavigationServiceDelegate {","    private var navigationService: NVNavigationService!","","    override func viewDidLoad() {","        navigationService = NVNavigationService(delegate: this)","    }","","    func navigationService(_ service: NVNavigationService, didStartWith progress: NVibeRouteProgress) {","        ","    }","","    ...","","    func navigationService(_ service: NVNavigationService, didStopWith progress: NVibeRouteProgress) {","        ","    }","}"]},{"anchor":"Start-the-walking-navigation","level":3,"type":"heading","text":"Start the walking navigation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To start the navigation service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/startNavigation(route:rerouteMode:changeStepMode:)"},{"type":"text","text":" method. Prior, you need to request a walking route. For more information, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getroute"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["var route: NVibeRoute","","navigationService.startNavigation(route: route)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the navigation service starts correctly, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStartWith:)"},{"type":"text","text":" method is called. Otherwise, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didFailToPassTokenWith:)"},{"type":"text","text":" method is called."}]},{"type":"codeListing","syntax":"swift","code":["func navigationService(_ service: NVNavigationService, didStartWith progress: NVibeRouteProgress) {","    \/\/The navigation service starts.","    print(\"Your navigation starts, \\(progress.stepProgress.nextStep?.maneuver.instruction) in \\(progress.stepProgress.remainingDistance) meters\")","    \/\/Your navigation starts, turn left in 50 meters.","}","","func navigationService(_ service: NVNavigationService, didFailToPassTokenWith error: NVDirectionKit.TokenError) {","    \/\/A error occurred.","}",""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user’s location updates, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdate:with:snappedTo:with:)"},{"type":"text","text":" method is called. You can update the user’s location on your map and update the information about instruction."}]},{"type":"codeListing","syntax":"swift","code":["func navigationService(_ service: NVNavigationService, didUpdate progress: NVibeRouteProgress, with rawLocation: CLLocation, snappedTo location: CLLocation, with uTurn: Bool) {","    print(\"The user moves to \\(location.coordinate)\")","    if uTurn {","        print(\"Make a U-turn then \\(progress.stepProgress.nextStep?.maneuver.instruction) in \\(progress.stepProgress.remainingDistance) meters\")","        \/\/Make a U-turn then turn left in 50 meters.","    } else {","        print(\"\\(progress.stepProgress.nextStep?.maneuver.instruction) in \\(progress.stepProgress.remainingDistance) meters\")","        \/\/Turn left in 50 meters.","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user will reach the next step, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:willChange:)"},{"type":"text","text":" method is called. The distance before the next step to trigger it is set with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/distanceBeforePrepareChangeStep"},{"type":"text","text":". You can inform the user about the next step."}]},{"type":"codeListing","syntax":"swift","code":["func navigationService(_ service: NVNavigationService, willChange progress: NVibeRouteProgress) {","    print(\"\\(progress.stepProgress.nextStep?.maneuver.instruction) in \\(progress.stepProgress.remainingDistance) meters\")","    \/\/Turn left in 25 meters.","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user reaches the next step, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didChange:)"},{"type":"text","text":" method is called. You can inform the user about what to do."}]},{"type":"codeListing","syntax":"swift","code":["func navigationService(_ service: NVNavigationService, didChange progress: NVibeRouteProgress) {","    print(\"\\(progress.stepProgress.currentStep.maneuver.instruction) now\")","    \/\/Turn left now.","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user reaches the arrival location, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStopWith:)"},{"type":"text","text":" method is called. You can inform the user that the navigation is finished and the destination is here."}]},{"type":"codeListing","syntax":"swift","code":["func navigationService(_ service: NVNavigationService, didStopWith progress: NVibeRouteProgress) {","    print(\"\\(progress.stepProgress.currentStep.maneuver.instruction)\")","    \/\/You've reached your destination, the destination is on your right","}"]},{"anchor":"Stop-the-walking-navigation","level":3,"type":"heading","text":"Stop the walking navigation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To stop the navigation service, use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/stopNavigation()"},{"type":"text","text":" method. If the user reaches their arrival location, the navigation service will stop automatically."}]},{"type":"codeListing","syntax":"swift","code":["navigationService.stopNavigation()"]},{"anchor":"Handle-reroute-from-walking-navigation","level":3,"type":"heading","text":"Handle reroute from walking navigation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user is too far from the initial route, a reroute can happen. First, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:shouldRerouteFrom:)"},{"type":"text","text":" method is called to confirm if you want to reroute or not. Then, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didRerouteAlong:with:)"},{"type":"text","text":" method is called if you accept to reroute and you can retrieve the new calculated route."}]},{"type":"codeListing","syntax":"swift","code":["func navigationService(_ service: NVNavigationService, shouldRerouteFrom location: CLLocation) -> Bool {","    return true \/\/true if you accept to reroute.","}","","func navigationService(_ service: NVNavigationService, didRerouteAlong route: NVibeRoute, with uTurn: Bool) {","    print(\"You are off route !\")","    if uTurn {","        print(\"Make a U-turn then \\(route.legs.first!.steps[1].maneuver.instruction) in \\(route.legs.first!.steps.first!.distance) meters\")","        \/\/Make a U-turn then turn right in 32 meters.","    } else {","        print(\"\\(route.legs.first!.steps[1].maneuver.instruction) in \\(route.legs.first!.steps.first!.distance) meters\")","        \/\/Turn right in 32 meters.","    }","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/usewalkingnavigation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvnavigationkit\/usewalkingnavigation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseWalkingNavigation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manage user’s progress over a walking navigation."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Starting walking navigation","role":"article","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/stopNavigation()":{"role":"symbol","title":"stopNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopNavigation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the generation of navigation updates."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/stopNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/stopnavigation()"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didStopWith:)":{"role":"symbol","title":"navigationService(_:didStopWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStopWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has stopped."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStopWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didstopwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"https://n-vibe.github.io/NVDirectionFramework/documentation/nvdirectionkit/getroute":{"title":"Getting walking route","titleInlineContent":[{"type":"text","text":"Getting walking route"}],"type":"link","identifier":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getroute","url":"https:\/\/n-vibe.github.io\/NVDirectionFramework\/documentation\/nvdirectionkit\/getroute"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/startNavigation(route:rerouteMode:changeStepMode:)":{"role":"symbol","title":"startNavigation(route:rerouteMode:changeStepMode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startNavigation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rerouteMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RerouteMode","preciseIdentifier":"s:15NVNavigationKit11RerouteModeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"changeStepMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChangeStepDetectionMode","preciseIdentifier":"s:15NVNavigationKit23ChangeStepDetectionModeO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the generation of updates that report the user’s progress during walking navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/startNavigation(route:rerouteMode:changeStepMode:)","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/startnavigation(route:reroutemode:changestepmode:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseMultimodalNavigation":{"role":"article","title":"Starting multimodal navigation","abstract":[{"type":"text","text":"Manage user’s progress over multimodal navigation by combining walking navigation and transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usemultimodalnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didRerouteAlong:with:)":{"role":"symbol","title":"navigationService(_:didRerouteAlong:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRerouteAlong"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has rerouted."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didRerouteAlong:with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didreroutealong:with:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didStartWith:)":{"role":"symbol","title":"navigationService(_:didStartWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has started."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didStartWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didstartwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didUpdate:with:snappedTo:with:)":{"role":"symbol","title":"navigationService(_:didUpdate:with:snappedTo:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"snappedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service has updated the user’s location."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didUpdate:with:snappedTo:with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didupdate:with:snappedto:with:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVCompassService":{"role":"symbol","title":"NVCompassService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVCompassService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of compass phone events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVCompassService"}],"url":"\/documentation\/nvnavigationkit\/nvcompassservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didChange:)":{"role":"symbol","title":"navigationService(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service reaches the next step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVMultimodalService":{"role":"symbol","title":"NVMultimodalService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVMultimodalService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of multimodal events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVMultimodalService"}],"url":"\/documentation\/nvnavigationkit\/nvmultimodalservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService/distanceBeforePrepareChangeStep":{"role":"symbol","title":"distanceBeforePrepareChangeStep","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceBeforePrepareChangeStep"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance in meter before receiving "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:willChange:)"},{"type":"text","text":". The default value of this property is "},{"type":"codeVoice","code":"25"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService\/distanceBeforePrepareChangeStep","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservice\/distancebeforepreparechangestep"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:didFailToPassTokenWith:)":{"role":"symbol","title":"navigationService(_:didFailToPassTokenWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToPassTokenWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TokenError","preciseIdentifier":"s:14NVDirectionKit10TokenErrorO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the navigation service was unable to start."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:didFailToPassTokenWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:didfailtopasstokenwith:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationService":{"role":"symbol","title":"NVNavigationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVNavigationService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of navigation events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVNavigationService"}],"url":"\/documentation\/nvnavigationkit\/nvnavigationservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:willChange:)":{"role":"symbol","title":"navigationService(_:willChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeRouteProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that navigation service will reach the next step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:willChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:willchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/UseTransitNavigation":{"role":"article","title":"Starting transit navigation","abstract":[{"type":"text","text":"Manage user’s progress over a transit navigation."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/usetransitnavigation"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvnavigationkit\/getstarted"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVNavigationServiceDelegate/navigationService(_:shouldRerouteFrom:)":{"role":"symbol","title":"navigationService(_:shouldRerouteFrom:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVNavigationService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVNavigationService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRerouteFrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks the delegate whether the navigation service should reroute."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationServiceDelegate\/navigationService(_:shouldRerouteFrom:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvnavigationservicedelegate\/navigationservice(_:shouldreroutefrom:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/GetStarted","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseTransitNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/UseMultimodalNavigation","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVNavigationService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVMultimodalService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVCompassService"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/title","value":"NVCompassService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVCompassService\/fragments","value":[{"kind":"identifier","text":"NVCompassService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/title","value":"NVMultimodalService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVMultimodalService\/fragments","value":[{"kind":"identifier","text":"NVMultimodalService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/title","value":"NVNavigationService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVNavigationService\/fragments","value":[{"kind":"identifier","text":"NVNavigationService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}