{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"service"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService","text":"NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress","text":"NVibeTransitProgress"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"service","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The transit service object that generated the update event."}]}]},{"name":"progress","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user’s progress over the transit navigation."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:willchange:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:willChange:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that transit service will reach the next stop."}],"kind":"symbol","metadata":{"role":"symbol","title":"transitService(_:willChange:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:15NVNavigationKit24NVTransitServiceDelegateP07transitD0_10willChangeyAA0cD0C_AA20NVibeTransitProgressCtF","required":true,"modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate"],["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate"]]},"seeAlsoSections":[{"title":"Receiving transit updates","identifiers":["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didUpdate:with:snappedTo:)","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didChange:)"],"generated":true}],"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:willChange:)":{"role":"symbol","title":"transitService(_:willChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service will reach the next stop."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:willChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:willchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate":{"role":"symbol","title":"NVTransitServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitServiceDelegate"}],"abstract":[{"type":"text","text":"The methods you use to receive events from an associated transit service object."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitServiceDelegate"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didChange:)":{"role":"symbol","title":"transitService(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service reaches the next stop."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didChange:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didchange:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitServiceDelegate/transitService(_:didUpdate:with:snappedTo:)":{"role":"symbol","title":"transitService(_:didUpdate:with:snappedTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitService"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NVTransitService","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVTransitService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeTransitProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"snappedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that transit service has updated the user’s location."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitServiceDelegate\/transitService(_:didUpdate:with:snappedTo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nvnavigationkit\/nvtransitservicedelegate\/transitservice(_:didupdate:with:snappedto:)"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVTransitService":{"role":"symbol","title":"NVTransitService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVTransitService"}],"abstract":[{"type":"text","text":"The object you use to start and stop the delivery of transit events to your app."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVTransitService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVTransitService"}],"url":"\/documentation\/nvnavigationkit\/nvtransitservice"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeTransitProgress":{"role":"symbol","title":"NVibeTransitProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the transit."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeTransitProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibetransitprogress"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/title","value":"NVTransitService"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVTransitService\/fragments","value":[{"kind":"identifier","text":"NVTransitService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeTransitProgress\/title","value":"NVibeTransitProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeTransitProgress\/fragments","value":[{"kind":"identifier","text":"NVibeTransitProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}