{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"obstacleProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeObstacleProgress","text":"NVibeObstacleProgress"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nviberouteprogress\/obstacleprogress"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/obstacleProgress","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"obstacleProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeObstacleProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeObstacleProgress"},{"kind":"text","text":"?"}],"title":"obstacleProgress","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:15NVNavigationKit18NVibeRouteProgressC08obstacleE0AA0c8ObstacleE0CSgvp","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress"]]},"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress/obstacleProgress":{"role":"symbol","title":"obstacleProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"obstacleProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeObstacleProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeObstacleProgress"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/obstacleProgress","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nviberouteprogress\/obstacleprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeObstacleProgress":{"role":"symbol","title":"NVibeObstacleProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacleProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step toward the next obstacle."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeObstacleProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacleProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibeobstacleprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress":{"role":"symbol","title":"NVibeRouteProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteProgress"}],"url":"\/documentation\/nvnavigationkit\/nviberouteprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/title","value":"NVibeObstacleProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeObstacleProgress\/fragments","value":[{"kind":"identifier","text":"NVibeObstacleProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/title","value":"NVibeRouteProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/fragments","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}