{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stepProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeStepProgress","text":"NVibeStepProgress"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvnavigationkit\/nviberouteprogress\/stepprogress"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/stepProgress","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stepProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeStepProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeStepProgress"}],"title":"stepProgress","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:15NVNavigationKit18NVibeRouteProgressC04stepE0AA0c4StepE0Cvp","modules":[{"name":"NVNavigationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress"]]},"references":{"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit":{"role":"collection","title":"NVNavigationKit","abstract":[{"type":"text","text":"Start TurnByTurn navigation from route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress/stepProgress":{"role":"symbol","title":"stepProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stepProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeStepProgress","preciseIdentifier":"c:@M@NVNavigationKit@objc(cs)NVibeStepProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress\/stepProgress","kind":"symbol","type":"topic","url":"\/documentation\/nvnavigationkit\/nviberouteprogress\/stepprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeStepProgress":{"role":"symbol","title":"NVibeStepProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStepProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking step."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeStepProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStepProgress"}],"url":"\/documentation\/nvnavigationkit\/nvibestepprogress"},"doc://com.nvibe.NVNavigationKit/documentation/NVNavigationKit/NVibeRouteProgress":{"role":"symbol","title":"NVibeRouteProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteProgress"}],"abstract":[{"type":"text","text":"The user’s progress along the walking route."}],"identifier":"doc:\/\/com.nvibe.NVNavigationKit\/documentation\/NVNavigationKit\/NVibeRouteProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteProgress"}],"url":"\/documentation\/nvnavigationkit\/nviberouteprogress"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/title","value":"NVibeStepProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeStepProgress\/fragments","value":[{"kind":"identifier","text":"NVibeStepProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/title","value":"NVibeRouteProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVNavigationKit~1documentation~1NVNavigationKit~1NVibeRouteProgress\/fragments","value":[{"kind":"identifier","text":"NVibeRouteProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}